services:
  - type: web
    name: money-track-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
